services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_AUTH_DISABLE_LOGIN_ATTEMPTS_LOCK=true

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml.template
    restart: unless-stopped
    env_file:
      - .env
    entrypoint:
      - /bin/sh
      - -c
      - |
        sed -e 's|\$${TELEGRAM_BOT_TOKEN}|'"$${TELEGRAM_BOT_TOKEN}"'|g' \
            -e 's|\$${TELEGRAM_CHAT_ID}|'"$${TELEGRAM_CHAT_ID}"'|g' \
            /etc/alertmanager/alertmanager.yml.template > /tmp/alertmanager.yml
        exec /bin/alertmanager --config.file=/tmp/alertmanager.yml

